name: PR

on:
  pull_request:

jobs:
  frontend:
    name: Frontend
    runs-on: ubuntu-latest
    container: node:20
    timeout-minutes: 30
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm run lint:check

      - name: Build
        run: pnpm run build

  backend:
    name: Backend
    runs-on: ubuntu-latest
    container: golang:1.24
    defaults:
      run:
        working-directory: ./backend
    timeout-minutes: 30
    steps:
      - name: Setup gcc
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build
        run: go build -buildvcs=false .

      - name: Test
        run: go test -v

      - uses: codecov/codecov-action@v3
